/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHECKCOOL_H_RPCGEN
#define _CHECKCOOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define checkCOOL 0x2fffffff
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define check 1
extern  char ** check_1(char **, CLIENT *);
extern  char ** check_1_svc(char **, struct svc_req *);
extern int checkcool_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define check 1
extern  char ** check_1();
extern  char ** check_1_svc();
extern int checkcool_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHECKCOOL_H_RPCGEN */
